service: serverless-tasks-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  all:
    handler: index.all
    events:
      - httpApi:
          path: /
          method: get
