service: serverless-tasks-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  getAllTasks:
    handler: handler.getAllTasks
    events:
      - httpApi:
          path: /tasks
          method: get

  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
