service: serverless-tasks-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  getAllTasks:
    handler: handler.getAllTasks
    events:
      - httpApi:
          path: /tasks
          method: get

  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post

  updateTask:
    handler: handler.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: patch

  completeTask:
    handler: handler.completeTask
    events:
      - httpApi:
          path: /tasks/{id}/complete
          method: post

  deleteTask:
    handler: handler.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete
